language: cpp

os: linux
dist: trusty

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq libpoco*
- sudo apt-get install -qq gcc-5 g++-5
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
- g++ --version
install:
- git clone https://github.com/CopernicaMarketingSoftware/AMQP-CPP.git
- cd ./AMQP-CPP && make && sudo make install && cd ..

before_script: mkdir build
script: make
